config/routes.rb
Rails.application.routes.draw do
  resources :comments
  get 'welcome/index'

  resources :recipe_books
  devise_for :users
  root "welcome#index"

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :recipe_book
end

app/models/recipe_book.rb
class RecipeBook < ActiveRecord::Base
  has_attached_file :photo, styles: { medium: "500x500>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
    validates_attachment_content_type :photo, content_type: /\Aimage\/.*\Z/

  belongs_to :user
  has_many :comments
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
has_many :recipe_books
has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:show, :edit, :update, :destroy]

  # GET /comments
  # GET /comments.json
  def index
    @comments = Comment.all
  end

  # GET /comments/1
  # GET /comments/1.json
  def show
  end

  # GET /comments/new
  def new
    @comment = Comment.new
  end

  # GET /comments/1/edit
  def edit
  end

  # POST /comments
  # POST /comments.json
  def create
    @comment = Comment.new(comment_params)

    respond_to do |format|
      if @comment.save
        format.html { redirect_to recipe_book_path(id: @comment.recipe_book_id), notice: 'Comment was successfully created.' }
        format.json { render :show, status: :created, location: @comment }
      else
        format.html { render :new }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comments/1
  # PATCH/PUT /comments/1.json
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to @comment, notice: 'Comment was successfully updated.' }
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to comments_url, notice: 'Comment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comment_params
      params.require(:comment).permit(:entry, :user_id, :recipe_book_id)
    end
end

app/controllers/recipe_books_controller.rb
class RecipeBooksController < ApplicationController
  before_action :set_recipe_book, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_user!
  # GET /recipe_books
  # GET /recipe_books.json
  def index
    @recipe_books = RecipeBook.all
  end

  # GET /recipe_books/1
  # GET /recipe_books/1.json
  def show
    @comment = Comment.new
  end

  # GET /recipe_books/new
  def new
    @recipe_book = RecipeBook.new
  end

  # GET /recipe_books/1/edit
  def edit
  end

  # POST /recipe_books
  # POST /recipe_books.json
  def create
    @recipe_book = RecipeBook.new(recipe_book_params)

    respond_to do |format|
      if @recipe_book.save
        format.html { redirect_to @recipe_book, notice: 'Recipe book was successfully created.' }
        format.json { render :show, status: :created, location: @recipe_book }
      else
        format.html { render :new }
        format.json { render json: @recipe_book.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /recipe_books/1
  # PATCH/PUT /recipe_books/1.json
  def update
    respond_to do |format|
      if @recipe_book.update(recipe_book_params)
        format.html { redirect_to @recipe_book, notice: 'Recipe book was successfully updated.' }
        format.json { render :show, status: :ok, location: @recipe_book }
      else
        format.html { render :edit }
        format.json { render json: @recipe_book.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /recipe_books/1
  # DELETE /recipe_books/1.json
  def destroy
    @recipe_book.destroy
    respond_to do |format|
      format.html { redirect_to recipe_books_url, notice: 'Recipe book was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_recipe_book
      @recipe_book = RecipeBook.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def recipe_book_params
      params.require(:recipe_book).permit(:title, :instructions, :ingredients, :rating, :user_id, :photo)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/recipe_books_helper.rb
module RecipeBooksHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/comments/_form.html.erb
<%= form_for(@comment) do |f| %>
  <% if @comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% @comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :entry %><br>
    <%= f.text_area :entry %>
  </div>
  <div class="cant-see-me">
    <%= f.number_field :user_id, value: current_user.id %>
    <%= f.number_field :recipe_book_id, value: @recipe_book.id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/comments/edit.html.erb
<h1>Editing Comment</h1>

<%= render 'form' %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>

app/views/comments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Comments</h1>

<table>
  <thead>
    <tr>
      <th>Entry</th>
      <th>User</th>
      <th>Recipe</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= comment.entry %></td>
        <td><%= comment.user_id %></td>
        <td><%= comment.recipe_id %></td>
        <td><%= link_to 'Show', comment %></td>
        <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
        <td><%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Comment', new_comment_path %>

app/views/comments/new.html.erb
<h1>New Comment</h1>

<%= render 'form' %>

<%= link_to 'Back', comments_path %>

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Entry:</strong>
  <%= @comment.entry %>
</p>

<p>
  <strong>User:</strong>
  <%= @comment.user_id %>
</p>

<p>
  <strong>Recipe:</strong>
  <%= @comment.recipe_id %>
</p>

<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%= link_to 'Back', comments_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Recipe</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/recipe_books/_form.html.erb
<%= form_for(@recipe_book) do |f| %>
  <% if @recipe_book.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@recipe_book.errors.count, "error") %> prohibited this recipe_book from being saved:</h2>

      <ul>
      <% @recipe_book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :instructions %><br>
    <%= f.text_area :instructions %>
  </div>
  <div class="field">
    <%= f.label :ingredients %><br>
    <%= f.text_area :ingredients %>
  </div>
  <div class="field">
    <%= f.label :rating %><br>
    <%= f.number_field :rating %>
  </div>
  <div class="field">
    <%= f.label :photo %><br>
    <%= f.file_field :photo %>
  </div>
  <div class="cant-see-me">
    <%= f.number_field :user_id, value: current_user.id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/recipe_books/edit.html.erb
<h1>Editing Recipe Book</h1>

<%= render 'form' %>

<%= link_to 'Show', @recipe_book %> |
<%= link_to 'Back', recipe_books_path %>

app/views/recipe_books/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Recipe Books</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Instructions</th>
      <th>Ingredients</th>
      <th>Rating</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @recipe_books.each do |recipe_book| %>
      <tr>
        <td><%= recipe_book.title %></td>
        <td><%= recipe_book.instructions %></td>
        <td><%= recipe_book.ingredients %></td>
        <td><%= recipe_book.rating %></td>
        <td><%= recipe_book.user.email %></td>
        <td><%= link_to 'Show', recipe_book %></td>
        <td><%= link_to 'Edit', edit_recipe_book_path(recipe_book) %></td>
        <td><%= link_to 'Destroy', recipe_book, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Recipe book', new_recipe_book_path %>

app/views/recipe_books/new.html.erb
<h1>New Recipe Book</h1>

<%= render 'form' %>

<%= link_to 'Back', recipe_books_path %>

app/views/recipe_books/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @recipe_book.title %>
</p>

<p>
  <strong>Instructions:</strong>
  <%= @recipe_book.instructions %>
</p>

<p>
  <strong>Ingredients:</strong>
  <%= @recipe_book.ingredients %>
</p>

<p>
  <strong>Rating:</strong>
  <%= @recipe_book.rating %>
</p>

<p>
  <strong>User:</strong>
  <%= @recipe_book.user.email %>
</p>

<%= image_tag @recipe_book.photo.url(:medium) %>

<%= link_to 'Edit', edit_recipe_book_path(@recipe_book) %> |
<%= link_to 'Back', recipe_books_path %>


<%= render 'comments/form' %>

<br />

<% @recipe_book.comments.each do |comment| %>
  <h2><%= comment.entry %></h2>
  <p>
  by <%= comment.user.email %>
  </p>
<% end %>

app/views/welcome/index.html.erb
<h1>Welcome#index</h1>
<p>Find me in app/views/welcome/index.html.erb</p>